name: DownLoad
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_NAME: v1.0.3
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          wget https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi
      
	    - name: commit
      run: |
        git config --global user.email 625726371@qq.com
        git config --global user.name mitags
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
