name: DownLoad
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  BUILD_NAME: v1.0.1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          wget https://chrome-infra-packages.appspot.com/dl/gn/gn/windows-amd64/+/latest
      
      - name: Upload Release (x64)
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{secrets.BUILD_TOKEN}}
        with:
          upload_url: https://uploads.github.com/repos/snfan/exam/releases/84256454/assets{?name,label}
          asset_path: strawberry-perl-5.32.1.1-32bit.msi
          asset_name: strawberry-perl-5.32.1.1-32bit.msi
          asset_content_type: application/octet-stream 
